on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu:latest
    steps:
      - name: Check git repository
        uses:actions/checkout@v2

      - name: Install node with a version 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: run lint to check if exists errors
        run:  npx eslint .